

from openai import OpenAI 
import json 


client = OpenAI(
    base_url="http://localhost:1234/v1",
    api_key="lm-studio" 
)


def main():
    models = client.models.list()
    for m in models.data:
        print(m.id)

    response = client.chat.completions.create(
       model="qwen3-0.6b",
       messages=[
           {"role": "system", "content": "You are helpful assistant. "}, # typical system prompt of a chatbot
           #{"role": "user", "content": "In Python, 0.1 + 0.2 == 0.3 is false. Explain in one sentence why?"}
           {"role": "user", "content": "Who predicted that The next era of information technology will be dominated by [IoT] devices?"}

           # Who forecast in 2004 that connected devices would take over the next generation of IT?
           # Who said IoT would dominate the future of information technology?

       ] 
    )

    print("Answer:")
    print(response.choices[0].message.content) 

def demo_multi_turn():
    messages=[
           {"role": "system", "content": "You are helpful assistant."}, # typical system prompt of a chatbot
       ]  
    for question in ["What is the capital of Pakistan?", "And its population?"]:
        messages.append({"role": "user", "content": question})
        response = client.chat.completions.create(
            model="qwen3-0.6b",
            messages=messages
        ) 
        answer = response.choices[0].message.content
        messages.append({"role": "assistant", "content": answer}) # marker, that answer was generated by AI
        print("user>", question)
        print("model>", {answer})


# In-context learning 

def demo_in_context():
    response = client.chat.completions.create(
            model="qwen3-0.6b", 
            messages=[
                {"role": "system", "content": "Follow the pattern shown in the examples."}, # system prompt for in-context learning
                {"role": "user", "content": "I need two monitors by Friday."}, # query
                {"role": "assistant", "content": '{"item": "monitor", "quantity": 2, "deadline", "Friday"}'}, # answer
                {"role": "user", "content": "Please send me one laptop, no rush."}, # query
                {"role": "assistant", "content": '{"item": "laptop", "quantity": 1, "deadline", "undefined"}'}, # answer
                {"role": "user", "content": "We require five docking stations by the end of September."}, 

            ]
    )
    print(response.choices[0].message.content) 


def demo_temperature(): # parameter of determinism 0.0 = (near-)deterministic, high values = creative 
    prompt = "Give a name for a coffee shop run by robots. Name only."

    for temp in [0.0, 0.0, 0.5, 0.5, 1.0, 1.0]:
        response = client.chat.completions.create(
            model="qwen3-0.6b",  
            messages=[
                {"role": "system", "content": "You are helpful assistant."},
                {"role": "user", "content": prompt}
            ],
            temperature= temp
        )
        print(response.choices[0].message.content)


def demo_structured_output():
    schema = {
        "type": "object", 
        "properties": {
            "item": {"type": "string"},
            "quantity": {"type": "integer"},
            "deadline": {"type": ["string", "null"]},
        },
        "required": ["item", "quantity", "deadline"]
    }

    response = client.chat.completions.create(
        model="qwen3-0.6b",
        messages=[
            {"role": "system", "content": "Extract the order: item = product name (singular), quantity = number, deadline = due date or null."},
            {"role": "user", "content": "We require five docking stations by the end of September."}    
        ],
        response_format={
            "type": "json_schema",
            "json_schema": {"name": "order", "schema": schema}
        },
        temperature=0.0,
    )
    order = json.loads(response.choices[0].message.content)
    print(order)
    print(order["quantity"], type(order["quantity"]))


def demo_tool_calling(): 

    def get_current_time():
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M")

    available_tools = {"get_current_time": get_current_time}
    
    tools = [
        {
            "type": "function",
            "function": {
                "name" : "get_current_time",
                "description": "Return the current local date and time",
                "parameters": {"type": "object", "properties": {}},
            }
        }
    ]

    messages = [
        {"role": "system", "content": "You are helpful assistant."},
        {"role": "user", "content": "What time is it right now?"}
    ]

    response = client.chat.completions.create(
        model= "qwen3-0.6b",
        messages=messages,
        tools=tools, 
        temperature=0.0,
    )
    msg = response.choices[0].message
    #print(msg.tool_calls[0].function.name)
    #print(msg.tool_calls[0].function.arguments)
    result = available_tools[msg.tool_calls[0].function.name]() # () -> actual function call

    messages.append(msg)
    messages.append({"role": "tool", "tool_call_id": msg.tool_calls[0].id, "content": result} )

    response = client.chat.completions.create(
        model="qwen3-0.6b", messages=messages, tools=tools, temperature=0.0)
    print(f"final answer:   {response.choices[0].message.content}")


def demo_tool_calling_python(model="qwen3-0.6b"):
    # harder tasks (e.g. "also print the first line of every .py file") overwhelm
    # the 0.6b model — it loops on its own syntax errors; use qwen/qwen3.5-35b-a3b then

    def run_python(code):
        import io, contextlib
        buffer = io.StringIO()
        try:
            with contextlib.redirect_stdout(buffer):
                exec(code, {})
        except Exception as e:
            return f"Error: {e}"
        return buffer.getvalue() or "(code produced no output — use print())"

    tools = [
        {
            "type": "function",
            "function": {
                "name": "run_python",
                "description": "Execute Python code and return what it prints. Use for any calculation.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "code": {"type": "string", "description": "Python code, must print() the result"}
                    },
                    "required": ["code"],
                },
            },
        }
    ]

    messages = [
        {"role": "system", "content": "You are a helpful assistant. To answer questions, write Python code and run it with the run_python tool."},
        {"role": "user", "content": "Which files are in the current directory?"}
    ]

    # agent loop: keep executing tool calls until the model answers in plain text
    for step in range(5):
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            tools=tools,
            temperature=0.0,
        )
        msg = response.choices[0].message

        if not msg.tool_calls:
            print(f"final answer:   {msg.content}")
            break

        # append a clean dict, not the raw msg object: LM Studio also returns
        # reasoning_content, which confuses the model when echoed back
        messages.append({
            "role": "assistant",
            "content": msg.content,
            "tool_calls": [tc.model_dump() for tc in msg.tool_calls],
        })
        for tool_call in msg.tool_calls:
            args = json.loads(tool_call.function.arguments)  # arguments arrive as JSON string
            print(f"--- step {step}: model wants to run ---")
            print(args["code"])

            # human in the loop: never exec model code without user approval
            if input("execute this code? [y/N] ").strip().lower() == "y":
                result = run_python(args["code"])
                print(f"interpreter output: {result}")
            else:
                result = "The user rejected the execution of this code."
                print("skipped.")
            messages.append({"role": "tool", "tool_call_id": tool_call.id, "content": result})


def summary_extraction():
    # TODO
    # Extract important dates and information structurally from the given text
    text = "The Silent Parade was a protest march in New York City on July 28, 1917. The goal was to draw attention to the racial violence and entrenched systemic discrimination endured by African Americans. The march was precipitated by racially motivated attacks in 1916 and 1917, including the East St. Louis massacre, and lynchings in Waco and in Memphis. The parade was organized by a coalition of African-American groups, led by the recently formed NAACP. Starting at 57th Street, the parade route proceeded down Fifth Avenue, ending at Madison Square. It was a silent procession, with an estimated 8,000 to 15,000 African Americans marching in protest, accompanied by a muffled drumbeat. Organizers hoped that the parade would prompt the federal government to enact anti-lynching legislation, but President Woodrow Wilson did not act on their demands. Lynchings persisted in the United States into the 1960s. "


#main()
demo_tool_calling_python()
#demo_multi_turn()
#demo_in_context()
#demo_temperature()
#demo_structured_output()
#demo_tool_calling()