

from openai import OpenAI 
import json 


client = OpenAI(
    base_url="http://localhost:1234/v1",
    api_key="lm-studio" 
)


def main():
    models = client.models.list()
    for m in models.data:
        print(m.id)

    response = client.chat.completions.create(
       model="qwen3-0.6b",
       messages=[
           {"role": "system", "content": "You are helpful assistant. Answer only in datetime format!"}, # typical system prompt of a chatbot
           #{"role": "user", "content": "In Python, 0.1 + 0.2 == 0.3 is false. Explain in one sentence why?"}
           {"role": "user", "content": "What time is it?"} 
       ] 
    )

    print("Answer:")
    print(response.choices[0].message.content) 

def demo_multi_turn():
    messages=[
           {"role": "system", "content": "You are helpful assistant."}, # typical system prompt of a chatbot
       ]  
    for question in ["What is the capital of Pakistan?", "And its population?"]:
        messages.append({"role": "user", "content": question})
        response = client.chat.completions.create(
            model="qwen3-0.6b",
            messages=messages
        ) 
        answer = response.choices[0].message.content
        messages.append({"role": "assistant", "content": answer}) # marker, that answer was generated by AI
        print("user>", question)
        print("model>", {answer})


# In-context learning 

def demo_in_context():
    response = client.chat.completions.create(
            model="qwen3-0.6b", 
            messages=[
                {"role": "system", "content": "Follow the pattern shown in the examples."}, # system prompt for in-context learning
                {"role": "user", "content": "I need two monitors by Friday."}, # query
                {"role": "assistant", "content": '{"item": "monitor", "quantity": 2, "deadline", "Friday"}'}, # answer
                {"role": "user", "content": "Please send me one laptop, no rush."}, # query
                {"role": "assistant", "content": '{"item": "laptop", "quantity": 1, "deadline", "undefined"}'}, # answer
                {"role": "user", "content": "We require five docking stations by the end of September."}, 

            ]
    )
    print(response.choices[0].message.content) 


def demo_temperature(): # parameter of determinism 0.0 = (near-)deterministic, high values = creative 
    prompt = "Give a name for a coffee shop run by robots. Name only."

    for temp in [0.0, 0.0, 0.5, 0.5, 1.0, 1.0]:
        response = client.chat.completions.create(
            model="qwen3-0.6b",  
            messages=[
                {"role": "system", "content": "You are helpful assistant."},
                {"role": "user", "content": prompt}
            ],
            temperature= temp
        )
        print(response.choices[0].message.content)


def demo_structured_output():
    schema = {
        "type": "object", 
        "properties": {
            "item": {"type": "string"},
            "quantity": {"type": "integer"},
            "deadline": {"type": ["string", "null"]},
        },
        "required": ["item", "quantity", "deadline"]
    }

    response = client.chat.completions.create(
        model="qwen3-0.6b",
        messages=[
            {"role": "system", "content": "Extract the order: item = product name (singular), quantity = number, deadline = due date or null."},
            {"role": "user", "content": "We require five docking stations by the end of September."}    
        ],
        response_format={
            "type": "json_schema",
            "json_schema": {"name": "order", "schema": schema}
        },
        temperature=0.0,
    )
    order = json.loads(response.choices[0].message.content)
    print(order)
    print(order["quantity"], type(order["quantity"]))




main()
#demo_multi_turn()
#demo_in_context()
#demo_temperature()
#demo_structured_output()